# Generated by Django 4.1.6 on 2023-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('INSTITUICAO', models.CharField(max_length=15)),
                ('nome_longo', models.CharField(max_length=15)),
                ('sigla', models.CharField(max_length=15)),
                ('ano', models.CharField(max_length=15)),
                ('UNIDADE', models.CharField(max_length=15)),
                ('NIVEL', models.CharField(max_length=15)),
                ('PAPEL', models.CharField(max_length=15)),
                ('USUARIO_ID', models.CharField(max_length=15)),
            ],
        ),
    ]
