# Generated by Django 4.2 on 2023-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DACMOOD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ra', models.CharField(max_length=35)),
                ('nome_curto', models.CharField(max_length=35)),
                ('papel', models.CharField(max_length=35)),
                ('instituicao', models.CharField(max_length=35)),
                ('nivel', models.CharField(max_length=35)),
                ('unidade', models.CharField(max_length=35)),
                ('hosp', models.CharField(max_length=35)),
            ],
        ),
    ]
