# Generated by Django 4.2 on 2023-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_socio_alter_dacmood_ra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='MATRICULA_RA',
            new_name='ra',
        ),
        migrations.AddField(
            model_name='socio',
            name='instituicao',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AddField(
            model_name='socio',
            name='nivel',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AddField(
            model_name='socio',
            name='nome_curto',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AddField(
            model_name='socio',
            name='papel',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AddField(
            model_name='socio',
            name='sigla_uni',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AddField(
            model_name='socio',
            name='unidade',
            field=models.CharField(default='NA', max_length=35),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
