# Generated by Django 4.2 on 2023-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_matricula_ra_socio_ra_socio_instituicao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOCIO',
        ),
    ]
