# Generated by Django 4.2 on 2023-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOCIO',
            fields=[
                ('ra', models.CharField(max_length=100)),
                ('SEXO', models.CharField(max_length=10)),
                ('COR_RACA', models.CharField(max_length=100)),
                ('ESC_FUNDAMENTAL1', models.CharField(max_length=100)),
                ('ESC_FUNDAMENTAL2', models.CharField(max_length=100)),
                ('ESC_MEDIO', models.CharField(max_length=100)),
                ('EST_CIVIL', models.CharField(max_length=100)),
                ('DATA_NASCIMENTO', models.CharField(max_length=100)),
                ('FILHOS', models.IntegerField()),
                ('RENDA_MES_FAMILIA', models.IntegerField()),
                ('CP', models.IntegerField()),
                ('CPE', models.IntegerField()),
                ('CR', models.IntegerField()),
                ('CRP', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_curto', models.CharField(default='NA', max_length=35)),
                ('papel', models.CharField(default='NA', max_length=35)),
                ('instituicao', models.CharField(default='NA', max_length=35)),
                ('nivel', models.CharField(default='NA', max_length=35)),
                ('unidade', models.CharField(default='NA', max_length=35)),
                ('sigla_uni', models.CharField(default='NA', max_length=35)),
            ],
        ),
    ]
