# Generated by Django 4.2 on 2023-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='CLASSE',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
