# Generated by Django 4.2 on 2023-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_socio_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='IDADE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
