# Generated by Django 4.2 on 2023-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_socio_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='ESTADO',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
