# Generated by Django 4.2 on 2023-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_socio_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MESO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MESORRE', models.CharField(max_length=100)),
                ('MUNICIPIO', models.CharField(max_length=100)),
            ],
        ),
    ]
